server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/education_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Muji2287300!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  security:
    user:
      name: admin
      password: 123456 # 这只是示例密码，生产环境应该使用更强的密码

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.education.entity,com.education.dto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false 

logging:
  level:
    root: INFO
    com.education: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG 